<a href="https://colab.research.google.com/github/manjotmb20/EC3/blob/master/magic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [45]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from numpy import linalg as LA
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from sklearn.preprocessing import StandardScaler
import nltk
nltk.download("punkt")
# Warnings
import warnings
warnings.filterwarnings('ignore')


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [46]:
data=pd.read_csv('data.csv')
data.head()

Unnamed: 0   fLength    fWidth   fSize  ...  fM3Trans   fAlpha     fDist  class
0           0   28.7967   16.0021  2.6449  ...   -8.2027  40.0920   81.8828      g
1           1   31.6036   11.7235  2.5185  ...   -9.9574   6.3609  205.2610      g
2           2  162.0520  136.0310  4.0612  ...  -45.2160  76.9600  256.7880      g
3           3   23.8172    9.5728  2.3385  ...   -7.1513  10.4490  116.7370      g
4           4   75.1362   30.9205  3.1611  ...   21.8393   4.6480  356.4620      g

[5 rows x 12 columns]

In [0]:
data= data.sample(frac=1).reset_index()


In [48]:
data.head(10)

index  Unnamed: 0  fLength   fWidth  ...  fM3Trans   fAlpha     fDist  class
0    487         487  32.0222   8.6668  ...  -10.2571  35.6250   43.7536      g
1   2012       17030  30.2501   8.1902  ...   -7.2522  43.9048  226.8710      h
2    456         456  73.2648  27.0787  ...   18.8744   6.2195  285.9970      g
3   1994        1994  48.0175  32.6580  ...   23.5773   8.7025  127.1720      g
4   3137       18155  29.2725  17.0724  ...  -18.5301  42.8316   23.7786      h
5   1924        1924  29.2823  12.9176  ...   -7.5543  16.8680  232.1640      g
6   3608       18626  56.4149  30.6338  ...  -27.3382  74.4429  190.0006      h
7   3572       18590  97.3859  45.1858  ...  -36.4356  32.3020  185.7120      h
8    147         147  18.2490  10.4383  ...    5.3027  15.8259  159.5440      g
9   1816        1816  26.5096  12.8159  ...    6.2608   7.5800  250.7210      g

[10 rows x 13 columns]

In [49]:
data['class'][data['class']=='g']=1
data['class'][data['class']=='h']=0
Y=pd.DataFrame(data['class'])
data.drop('class', inplace=True,axis=1)
data.drop('Unnamed: 0', inplace=True,axis=1)
data.drop('index', inplace=True,axis=1)
X=pd.DataFrame()
X=data
X.head()

fLength   fWidth   fSize   fConc  ...  fM3Long  fM3Trans   fAlpha     fDist
0  32.0222   8.6668  2.3454  0.4966  ... -23.0419  -10.2571  35.6250   43.7536
1  30.2501   8.1902  2.4864  0.5873  ...  23.6409   -7.2522  43.9048  226.8710
2  73.2648  27.0787  3.5292  0.1718  ...  67.9722   18.8744   6.2195  285.9970
3  48.0175  32.6580  3.4379  0.1791  ...  37.0195   23.5773   8.7025  127.1720
4  29.2725  17.0724  2.3220  0.4791  ... -28.5093  -18.5301  42.8316   23.7786

[5 rows x 10 columns]

In [50]:
Y

class
0        1
1        0
2        1
3        1
4        0
...    ...
3997     1
3998     0
3999     0
4000     0
4001     1

[4002 rows x 1 columns]

In [51]:
sc=StandardScaler()
X=sc.fit_transform(X)
X

array([[-0.53959929, -0.70525587, -1.06284197, ..., -0.44331417,
         0.13445696, -1.9873383 ],
       [-0.5762194 , -0.72667168, -0.76629186, ..., -0.3208851 ,
         0.43862064,  0.40946888],
       [ 0.31267111,  0.12207447,  1.42691706, ...,  0.7435947 ,
        -0.94577266,  1.18336378],
       ...,
       [-0.86917197, -0.77393832, -1.01636142, ..., -0.33012972,
        -0.34935131, -0.74732899],
       [ 0.81164562,  1.59304723,  2.05976763, ..., -2.32812456,
        -0.28283778,  1.40866712],
       [-0.79179054, -0.76356743, -1.45929372, ...,  0.18140044,
        -0.51781357,  0.711129  ]])

In [0]:
X_train=data
Y_train=Y['class']
Y_train=Y_train.astype('int')

In [53]:
type(Y_train)

pandas.core.series.Series

In [54]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
classifier3=DecisionTreeClassifier()
from sklearn.metrics import roc_auc_score,accuracy_score
x_train,x_val,y_train,y_val=train_test_split(X_train,Y_train,stratify=Y['class'],test_size=0.4,random_state=9)
classifier=LogisticRegression(C=5.0,random_state=0)
classifier.fit(x_train,y_train)
ypred=classifier.predict(x_val)
print("Accuracy score of LR",accuracy_score(y_val,ypred))
y_prob=classifier.predict_proba(x_val)
df=pd.DataFrame()
df['pred']=ypred
survived=pd.get_dummies(df.pred,prefix='Survived')
df=pd.concat([df,survived],axis=1)
df.drop('pred',inplace=True,axis=1)
df2=pd.DataFrame()
classifier3.fit(x_train,y_train)
ypred3=classifier3.predict(x_val)
print("Accuracy score of Decision Tree",accuracy_score(y_val,ypred3))
df2['pred']=ypred3
y_prob3=classifier3.predict_proba(x_val)
survived2=pd.get_dummies(df2.pred,prefix='Surviveds')
df=pd.concat([df,survived2],axis=1)
df

Accuracy score of LR 0.7607745159275453
Accuracy score of Decision Tree 0.7813866333541537


Survived_0  Survived_1  Surviveds_0  Surviveds_1
0              0           1            0            1
1              0           1            0            1
2              1           0            1            0
3              1           0            1            0
4              0           1            1            0
...          ...         ...          ...          ...
1596           0           1            0            1
1597           0           1            0            1
1598           1           0            1            0
1599           1           0            1            0
1600           0           1            0            1

[1601 rows x 4 columns]

In [0]:
m=np.array(df)
s=np.zeros(shape=(m.shape[0],m.shape[0]))
for i in range(m.shape[0]):
  for j in range(m.shape[0]):
    if i!=j:
      sum1=0
      for k in range(2,m.shape[1]):
        sum1=sum1+(m[i][k]*m[j][k])
      s[i][j]=sum1
w=s
d=np.zeros(shape=w.shape[0])


In [0]:
for i in range(d.shape[0]):
  d[i]=np.sum(w[i],axis=0)
wnew=w/d.reshape(d.shape[0],1)
Km=wnew     

In [57]:
Km

array([[0.        , 0.00122399, 0.        , ..., 0.        , 0.        ,
        0.00122399],
       [0.00122399, 0.        , 0.        , ..., 0.        , 0.        ,
        0.00122399],
       [0.        , 0.        , 0.        , ..., 0.00127877, 0.00127877,
        0.        ],
       ...,
       [0.        , 0.        , 0.00127877, ..., 0.        , 0.00127877,
        0.        ],
       [0.        , 0.        , 0.00127877, ..., 0.00127877, 0.        ,
        0.        ],
       [0.00122399, 0.00122399, 0.        , ..., 0.        , 0.        ,
        0.        ]])

**Checking whether the matrices have been normalized or not i.e making them bistochastic **

In [58]:
print(np.sum(Km,axis=1))
print(np.sum(Km,axis=0))

[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]


Similarly for Kc we generate a bistochastic matrix where m=the co-occurence matrix.

In [0]:

m=m.dot(m.T)  
s=np.zeros(shape=(m.shape[0],m.shape[0]))
for i in range(m.shape[0]):
  for j in range(m.shape[0]):
    if i!=j:
      sum1=0
      for k in range(2,m.shape[1]):
        sum1=sum1+(m[i][k]*m[j][k])
      s[i][j]=sum1   


In [60]:
d=np.zeros(shape=w.shape[0])
w=s
for i in range(d.shape[0]):
  d[i]=np.sum(w[i],axis=0)
wnew=w/d.reshape(d.shape[0],1)  
Kc=wnew
Kc

array([[0.        , 0.00104128, 0.0001439 , ..., 0.0001439 , 0.0001439 ,
        0.00104128],
       [0.00104128, 0.        , 0.0001439 , ..., 0.0001439 , 0.0001439 ,
        0.00104128],
       [0.00018306, 0.00018306, 0.        , ..., 0.00113059, 0.00113059,
        0.00018306],
       ...,
       [0.00018306, 0.00018306, 0.00113059, ..., 0.        , 0.00113059,
        0.00018306],
       [0.00018306, 0.00018306, 0.00113059, ..., 0.00113059, 0.        ,
        0.00018306],
       [0.00104128, 0.00104128, 0.0001439 , ..., 0.0001439 , 0.0001439 ,
        0.        ]])

**Same, checking for bi-stochastic behaviour**

In [61]:
  np.sum(Kc,axis=1)

array([1., 1., 1., ..., 1., 1., 1.])

**Generating Fg and Fo i'e the Group class matrix and Object Class matrix**

In [62]:

objclass_mat1=pd.DataFrame(y_prob,columns=['Survived','NotSurvived'])
objclass_mat2=pd.DataFrame(y_prob3,columns=['Survived','NotSurvived'])
df_t=pd.DataFrame(objclass_mat1)
Fo=np.array(df_t)
gpclass_mat=pd.DataFrame(columns=['Survived','NotSurvived'],index=['class1surv','class1notsurv','class2surv','class2notsurv'])
prob1s=np.sum(objclass_mat1.Survived)/len(objclass_mat1)
prob1ns=np.sum(objclass_mat1.NotSurvived)/len(objclass_mat1)
prob2s=np.sum(objclass_mat2.Survived)/len(objclass_mat2)
prob2ns=np.sum(objclass_mat2.NotSurvived)/len(objclass_mat2)
list1=[]
list1.append(prob1s)
list1.append(prob1ns)
list1.append(prob2s)
list1.append(prob2ns)

list2=[]
list2.append(prob1ns)
list2.append(prob1s)
list2.append(prob2ns)
list2.append(prob2s)
gpclass_mat['Survived']=list1
gpclass_mat['NotSurvived']=list2
gpclass_mat
Fg=np.array(gpclass_mat)
Fg

array([[0.49993433, 0.50006567],
       [0.50006567, 0.49993433],
       [0.48906933, 0.51093067],
       [0.51093067, 0.48906933]])

**Similarly, generating  Yo and Yg**

In [0]:
n=2
C=survived.shape[1]
G=survived.shape[1]*n

Yo=np.zeros(shape=(df.shape[0],C))
cal_y=np.array(df)
for i in range(Yo.shape[0]):
  Yo[i][0]=(cal_y[i][0]+cal_y[i][2])/C
for i in range(Yo.shape[0]):
  Yo[i][1]=(cal_y[i][1]+cal_y[i][3])/C

In [64]:
G

4

In [65]:
m=np.array(df)
Yg=np.zeros(shape=(m.shape[1],2))
c=np.sum(m,axis=0)
for i in range(Yg.shape[0]):
  if i%2==0:
    Yg[i][0]=c[i]/m.shape[0]
    Yg[i][1]=1-Yg[i][0]
  else:
    Yg[i][1]=c[i]/m.shape[0]
    Yg[i][0]=1-Yg[i][1]  
Yg

array([[0.44097439, 0.55902561],
       [0.44097439, 0.55902561],
       [0.48906933, 0.51093067],
       [0.48906933, 0.51093067]])

Genearting 

Checking for the conditions specified in eq 6

In [66]:
Fo_cond=True
Fg_cond=True
for i in range(Fo.shape[0]):
  if np.linalg.norm((Fo[i]), ord=1)!=1:
    Fo_cond=False
for i in range(Fg.shape[0]):
  if np.linalg.norm((Fg[i]), ord=1)!=1:
    Fo_cond=False    
print(Fo_cond)
print(Fg_cond)

True
True


**Generating diagonal matrices Dm and Dc**

In [67]:
test_dm=np.zeros(shape=(Km.shape))
test_Km=Km
for i in range(test_Km.shape[0]):
  test_dm[i]=np.sum(test_Km[i],axis=0)
Dm=np.diag(np.diag(test_dm))
print("Shape of DM",Dm.shape)
test_dc=np.zeros(shape=(Kc.shape))
test_Kc=Kc
for i in range(test_Kc.shape[0]):
  test_dc[i]=np.sum(test_Kc[i],axis=0)
Dc=np.diag(np.diag(test_dc))
print("shape of Dc",Dc.shape)

Shape of DM (1601, 1601)
shape of Dc (1601, 1601)


In [68]:
print("KHM",Km.shape)
print("KHC",Kc.shape)
print("Fo",Fo.shape)
print("Fg",Fg.shape)
print("Yo",Yo.shape)
print("Yg",Yg.shape)
print("Dm",Dm.shape)
print("Dc",Dc.shape)

KHM (1601, 1601)
KHC (1601, 1601)
Fo (1601, 2)
Fg (4, 2)
Yo (1601, 2)
Yg (4, 2)
Dm (1601, 1601)
Dc (1601, 1601)


In [69]:

Yg=np.pad(Yg,pad_width=[(0, Km.shape[0]-G), (0, 0)])
Yg.shape

(1601, 2)

In [70]:
print("KHM",Km.shape)
print("KHC",Kc.shape)
print("Fo",Fo.shape)
print("Fg",Fg.shape)
print("Yo",Yo.shape)
print("Yg",Yg.shape)
print("Dm",Dm.shape)
print("Dc",Dc.shape)

KHM (1601, 1601)
KHC (1601, 1601)
Fo (1601, 2)
Fg (4, 2)
Yo (1601, 2)
Yg (1601, 2)
Dm (1601, 1601)
Dc (1601, 1601)


In [0]:
import sys
threshold=sys.float_info.epsilon

**Implementing algorithm 2**

In [0]:
alpha=0.15
beta=0.35
gamma=0.40
delta=0.10
Fo_t=np.zeros(shape=Fo.shape)
Fg_t=np.zeros(shape=Fg.shape)
Fot_old=np.zeros(shape=Fo.shape)
Fo_t=Fo
Fg_t=Fg
while LA.norm((Fo_t-Fot_old),'fro')>threshold:
  Fot_old=Fo_t
  Fg_t=np.matmul((np.linalg.inv(2*delta*np.ones(shape=Dm.shape)+(alpha*Dm))),((alpha*np.matmul(Km,Fo_t))+(2*delta*Yg)))
  Fo_t=np.matmul((np.linalg.inv((alpha*Dm)+(2*beta*Dc)-(beta*np.matmul(np.identity(Kc.shape[0]),Kc))-(beta*np.matmul(np.ones(shape=Kc.shape),Kc))+(2*gamma*np.identity(Kc.shape[0])))),((alpha*np.matmul(Km,Fg_t))+(2*gamma*Yo)))

In [73]:
from sklearn.metrics import accuracy_score
result=np.zeros(shape=Fo_t.shape[0])
for i in range(Fo_t.shape[0]):
  if Fo_t[i][0]<Fo_t[i][1]:
    result[i]=1
print("Accuracy value for Ensemble model",accuracy_score(y_val,result))
print("AUC for for Ensemble model",roc_auc_score(y_val,result))
print("Accuracy value for LR",accuracy_score(y_val,ypred))
print("AUC for for LR",roc_auc_score(y_val,ypred))



Accuracy value for Ensemble model 0.778263585259213
AUC for for Ensemble model 0.7782045880149813
Accuracy value for LR 0.7607745159275453
AUC for for LR 0.7608114856429462


**We see that the ensemble model performs better than the Random forest, Kneigbours and Svm models and is at par with the Logistic regression model that gives us the best accuracy. **