<a href="https://colab.research.google.com/github/manjotmb20/EC3/blob/master/paddedmodelling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from numpy import linalg as LA

dataset=pd.read_csv('train.csv')

dataset2=pd.read_csv('test.csv')
dataset=dataset.fillna(dataset.mean())
dataset2=dataset2.fillna(dataset2.mean())
embarked=pd.get_dummies(dataset.Embarked,prefix='Embarked')
embarked2=pd.get_dummies(dataset2.Embarked,prefix='Embarked')
dataset=pd.concat([dataset,embarked],axis=1)
dataset2=pd.concat([dataset2,embarked2],axis=1)
dataset.drop(['Cabin', 'Ticket','Embarked','Name','PassengerId'],axis=1, inplace=True)
dataset2.drop(['Cabin', 'Ticket','Embarked','Name','PassengerId'],axis=1, inplace=True)
lc=LabelEncoder()
dataset[['Sex']]=lc.fit_transform(dataset[['Sex']])
dataset2[['Sex']]=lc.transform(dataset2[['Sex']])
sc=StandardScaler()
dataset[['Fare']]=sc.fit_transform(dataset[['Fare']])
dataset2[['Fare']]=sc.transform(dataset2[['Fare']])
sc1=StandardScaler()
dataset[['Age']]=sc1.fit_transform(dataset[['Age']])
dataset2[['Age']]=sc1.transform(dataset2[['Age']])
df_test=dataset['Survived']
df_train=dataset.drop('Survived',axis=1)
test=dataset2

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/label.py:252: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [3]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import roc_auc_score,accuracy_score
x_train,x_val,y_train,y_val=train_test_split(df_train,df_test,test_size=0.2,random_state=9)
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=2,init='k-means++')
kmeans.fit(x_train,y_train)
k_pred=kmeans.predict(x_val)
accuracy_score(y_val,k_pred)
df_kmeans=pd.DataFrame()
df_kmeans['Survived_k']=k_pred
survivedk=pd.get_dummies(df_kmeans.Survived_k,prefix='Survivedk')
classifier=LogisticRegression(random_state=0)
classifier.fit(x_train,y_train)
ypred=classifier.predict(x_val)
y_prob=classifier.predict_proba(x_val)
df=pd.DataFrame()
df['pred']=ypred
classifier1=DecisionTreeClassifier()
classifier1.fit(x_train,y_train)
ypred1=classifier1.predict(x_val)
df['pred2']=ypred1
y_prob2=classifier1.predict_proba(x_val)
print(roc_auc_score(y_val,ypred1))
print(accuracy_score(y_val,ypred1))

survived=pd.get_dummies(df.pred,prefix='Survived')
survived_classifier2=pd.get_dummies(df.pred2,prefix='Survsecond')
df=pd.concat([df,survived],axis=1)
df=pd.concat([df,survived_classifier2],axis=1)
df.drop(['pred','pred2','Survsecond_0','Survsecond_1'],axis=1,inplace=True)
df['Survivedk_0']=survivedk['Survivedk_0']
df['Survivedk_1']=survivedk['Survivedk_1']

0.7377848101265823
0.7486033519553073


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [4]:
df

Survived_0  Survived_1  Survivedk_0  Survivedk_1
0             1           0            1            0
1             1           0            1            0
2             1           0            1            0
3             1           0            0            1
4             0           1            1            0
..          ...         ...          ...          ...
174           0           1            1            0
175           0           1            1            0
176           1           0            1            0
177           0           1            0            1
178           0           1            1            0

[179 rows x 4 columns]

In [0]:
m=np.array(df)
s=np.zeros(shape=(m.shape[0],m.shape[0]))
for i in range(m.shape[0]):
  for j in range(m.shape[0]):
    if i!=j:
      sum1=0
      for k in range(2,m.shape[1]):
        sum1=sum1+(m[i][k]*m[j][k])
      s[i][j]=sum1
w=s
d=np.zeros(shape=w.shape[0])
for i in range(d.shape[0]):
  d[i]=np.sum(w[i],axis=0)
wnew=w/d.reshape(d.shape[0],1)
Km=wnew        

In [9]:
np.sum(Km,axis=0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1.])

Similarly finding Kc

In [21]:
m=np.array(df)
s=np.zeros(shape=(m.shape[0],m.shape[0]))
for i in range(m.shape[0]):
  for j in range(m.shape[0]):
    if i!=j:
      sum1=0
      for k in range(2,m.shape[1]):
        sum1=sum1+(m[i][k]*m[j][k])
      s[i][j]=sum1
m=s   
s=np.zeros(shape=(m.shape[0],m.shape[0]))
for i in range(m.shape[0]):
  for j in range(m.shape[0]):
    if i!=j:
      sum1=0
      for k in range(2,m.shape[1]):
        sum1=sum1+(m[i][k]*m[j][k])
      s[i][j]=sum1   
d=np.zeros(shape=w.shape[0])
w=s
for i in range(d.shape[0]):
  d[i]=np.sum(w[i],axis=0)
wnew=w/d.reshape(d.shape[0],1)  
Kc=wnew
Kc

array([[0.        , 0.00769231, 0.00763314, ..., 0.00763314, 0.        ,
        0.00763314],
       [0.00769231, 0.        , 0.00763314, ..., 0.00763314, 0.        ,
        0.00763314],
       [0.00769231, 0.00769231, 0.        , ..., 0.00763268, 0.        ,
        0.00763268],
       ...,
       [0.00769231, 0.00769231, 0.00763268, ..., 0.        , 0.        ,
        0.00763268],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.00769231, 0.00769231, 0.00763268, ..., 0.00763268, 0.        ,
        0.        ]])

In [22]:
np.sum(Kc,axis=1)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
objclass_mat1=pd.DataFrame(y_prob,columns=['Survived','NotSurvived'])
objclass_mat2=pd.DataFrame(y_prob2,columns=['Survived','NotSurvived'])
df_t=pd.DataFrame(objclass_mat1)
Fo=np.array(df_t)
gpclass_mat=pd.DataFrame(columns=['Survived','NotSurvived'],index=['class1surv','class1notsurv','class2surv','class2notsurv'])
prob1s=np.sum(objclass_mat1.Survived)/len(objclass_mat1)
prob1ns=np.sum(objclass_mat1.NotSurvived)/len(objclass_mat1)
prob2s=np.sum(objclass_mat2.Survived)/len(objclass_mat2)
prob2ns=np.sum(objclass_mat2.NotSurvived)/len(objclass_mat2)
list1=[]
list1.append(prob1s)
list1.append(prob1ns)
list1.append(prob2s)
list1.append(prob2ns)

list2=[]
list2.append(prob1ns)
list2.append(prob1s)
list2.append(prob2ns)
list2.append(prob2s)
gpclass_mat['Survived']=list1
gpclass_mat['NotSurvived']=list2
gpclass_mat
Fg=np.array(gpclass_mat)
Fg

array([[0.62706492, 0.37293508],
       [0.37293508, 0.62706492],
       [0.61527002, 0.38472998],
       [0.38472998, 0.61527002]])

In [0]:
C=2
G=4
Yg=np.zeros(shape=gpclass_mat.shape)
thres=0.5
for i in range(Fg.shape[0]):
  for j in range(Fg.shape[1]):
    if Fg[i][j]>thres:
      Yg[i][j]=1
Yo=np.zeros(shape=(179,2))
cal_y=np.array(df)
for i in range(Yo.shape[0]):
  Yo[i][0]=(cal_y[i][0]+cal_y[i][2])/C
for i in range(Yo.shape[0]):
  Yo[i][1]=(cal_y[i][1]+cal_y[i][3])/C

In [17]:
Yo.shape

(179, 2)

In [19]:
Yg

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.]])

In [23]:
print("KHM",Km.shape)
print("KHC",Kc.shape)
print("Fo",Fo.shape)
print("Fg",Fg.shape)
print("Yo",Yo.shape)
print("Yg",Yg.shape)

KHM (179, 179)
KHC (179, 179)
Fo (179, 2)
Fg (4, 2)
Yo (179, 2)
Yg (4, 2)


In [24]:
Fo_cond=True
Fg_cond=True
for i in range(Fo.shape[0]):
  if np.linalg.norm((Fo[i]), ord=1)!=1:
    Fo_cond=False
for i in range(Fg.shape[0]):
  if np.linalg.norm((Fg[i]), ord=1)!=1:
    Fo_cond=False    
print(Fo_cond)
print(Fg_cond)

True
True


In [28]:
np.linalg.norm((Yo[178]), ord=1)

1.0

In [33]:
J1=0
for i in range(Km.shape[0]):
  for j in range(Fg.shape[0]):
    J1=J1+Km[i][j]*(np.linalg.norm((Fo[i]-Fg[j]), ord=2)**2)
J2=0
for i in range(Kc.shape[0]):
  for j in range(Kc.shape[1]):
    J2=J2+Kc[i][j]*(np.linalg.norm((Fo[i]-Fo[j]), ord=2)**2)    
J3=0
for i in range(Kc.shape[0]):
  J3=J3+(np.linalg.norm((Fo[i]-Yo[i]), ord=2)**2) 

J4=0
for i in range(Yg.shape[0]):
  J4=J4+(np.linalg.norm((Fg[i]-Yg[i]), ord=2)**2) 
print(J1)
print(J2)
print(J3)
print(J4)

0.8259921444209362
55.62360291900236
16.89220861952216
1.1483909446340883


In [37]:
test_dm=np.zeros(shape=(Km.shape))
test_Km=Km
for i in range(test_Km.shape[0]):
  test_dm[i]=np.sum(test_Km[i],axis=0)
Dm=np.diag(np.diag(test_dm))
print("Shape of DM",Dm.shape)
test_dc=np.zeros(shape=(Kc.shape))
test_Kc=Kc
for i in range(test_Kc.shape[0]):
  test_dc[i]=np.sum(test_Kc[i],axis=0)
Dc=np.diag(np.diag(test_dc))
print("shape of Dc",Dc.shape)

Shape of DM (179, 179)
shape of Dc (179, 179)


In [43]:
print("KHM",Km.shape)
print("KHC",Kc.shape)
print("Fo",Fo.shape)
print("Fg",Fg.shape)
print("Yo",Yo.shape)
print("Yg",Yg.shape)
print("Dm",Dm.shape)
print("Dc",Dc.shape)

KHM (179, 179)
KHC (179, 179)
Fo (179, 2)
Fg (4, 2)
Yo (179, 2)
Yg (4, 2)
Dm (179, 179)
Dc (179, 179)


In [61]:
Yg=np.pad(Yg,pad_width=[(0, 175), (0, 0)])
Yg.shape

(179, 2)

In [63]:
print("KHM",Km.shape)
print("KHC",Kc.shape)
print("Fo",Fo.shape)
print("Fg",Fg.shape)
print("Yo",Yo.shape)
print("Yg",Yg.shape)
print("Dm",Dm.shape)
print("Dc",Dc.shape)

KHM (179, 179)
KHC (179, 179)
Fo (179, 2)
Fg (4, 2)
Yo (179, 2)
Yg (179, 2)
Dm (179, 179)
Dc (179, 179)


In [0]:
import sys
threshold=sys.float_info.epsilon

In [0]:
alpha=0.20
beta=0.35
gamma=0.45
delta=0.20
Fo_t=np.zeros(shape=Fo.shape)
Fg_t=np.zeros(shape=Fg.shape)
Fot_old=np.zeros(shape=Fo.shape)
Fo_t=Fo
Fg_t=Fg
while LA.norm((Fo_t-Fot_old),'fro')>threshold:
  Fot_old=Fo_t
  Fg_t=np.matmul((np.linalg.inv(2*delta*np.ones(shape=Dm.shape)+(alpha*Dm))),((alpha*np.matmul(Km,Fo))+(2*delta*Yg)))
  Fo_t=np.matmul((np.linalg.inv((alpha*Dm)+(2*beta*Dc)-(beta*np.matmul(np.identity(Kc.shape[0]),Kc))-(beta*np.matmul(np.ones(shape=Kc.shape),Kc))+(2*gamma*np.identity(Kc.shape[0])))),((alpha*np.matmul(Km,Fg_t))+(2*gamma*Yo)))

In [71]:
from sklearn.metrics import accuracy_score
result=np.zeros(shape=Fo_t.shape[0])
for i in range(Fo_t.shape[0]):
  if Fo_t[i][0]<Fo_t[i][1]:
    result[i]=1
print("AUC value",roc_auc_score(y_val,result))
print("AUC for model1",roc_auc_score(y_val,ypred))
print("AUC value",accuracy_score(y_val,result))
print("AUC for model1",accuracy_score(y_val,ypred))

AUC value 0.7560759493670887
AUC for model1 0.7627848101265823
AUC value 0.7541899441340782
AUC for model1 0.776536312849162
